name: Python CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0

jobs:
  test:
    runs-on: ubuntu-latest  # You can change to other operating systems if needed

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # You can specify the version you are using

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt file
    
    # Step 4: Run tests (using pytest in this case)
    - name: Run tests
      run: |
        pytest  # You can customize this with any test command you use

    # Step 5: Install flake8 for syntax checking
    - name: Install flake8
      run: |
        python -m pip install flake8

    # Step 6: Run Flake8 (for code linting)
    - name: Run Flake8
      run: |
        flake8 .  # Specify the directory or files to check

    # Step 7: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub Secrets

    # Step 8: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .  # Build and tag the image with your Docker Hub username

    # Step 9: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Push the image to Docker Hub using the correct tag

    # Step 10: Send email on failure (optional)
    - name: Send email on failure 
      if: failure()  # This step only runs if the previous steps fail
      run: |
        echo "Subject: GitHub Actions Failure Notification" > email.txt
        echo "The GitHub Actions workflow failed. Please check the logs." >> email.txt
        echo "Job: ${{ github.workflow }}" >> email.txt
        echo "Commit: ${{ github.sha }}" >> email.txt
        echo "Run URL: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}" >> email.txt
        
        # Send email using Gmail (ensure you have set up secrets for GMAIL_USER and GMAIL_PASSWORD)
        sendmail -S smtp.gmail.com:587 -f ${{ secrets.GMAIL_USER }} -t "shubhamdev098@gmail.com" \
        -au${{ secrets.GMAIL_USER }} -ap${{ secrets.GMAIL_PASSWORD }} < email.txt