trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addTopath: true

- script: |
    sudo apt-get update
    sudo apt-get install -y python3-distutils
  displayName: 'Install distutils' 

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

# Step 3: Run tests and generate test results
- script: |
    pytest --junitxml=test-results.xml  # Generate test result in XML format
  displayName: 'Run Tests'

# Step 4: Copy test results to artifact staging directory
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/test-results
    cp test-results.xml $(Build.ArtifactStagingDirectory)/test-results/  # Copy the test result file
  displayName: 'Copy Test Results to Staging Directory'

# Step 5: Publish test results (for reporting in pipeline)
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'  # Correct path to the test result file
    testRunTitle: 'Python Test Run'
    mergeTestResults: true

# Step 6: Publish build artifacts (including test results)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/test-results  # Path to the staged test results
    ArtifactName: 'test-results'
    publishLocation: 'Container'  # Publish the artifact in Azure DevOps container

 